### ISSUE TITLE
Help with resolving anonymous namespaces?

### ISSUE THREAD

**Issue by mjurkus** [ngallagher/simplexml#14]
I have an xml like this

```
<root>
  <item>
    <media:thumbnail>thumbnail_url</media:thumbnail>
  </item>
</root>
```

I can't seem to find a way how to parse such xml correctly.
Now I'm using such class:

```
@Root(name = "item")
public class ArticleSummary {

    @Element
    @Namespace(prefix = "media")
    private String thumbnail;
}
```

But I'm keep getting `XmlPullParserException: undefined prefix: media` error.

What should I do differently?

**Comment by ngallagher** [comment]
You need to define the namespace, @Namespace(prefix="x", reference="http://mynamespace"), fyi this exception is thrown from the XML parser not Simple XML.

```
  From: Martynas Jurkus <notifications@github.com>
```

 To: ngallagher/simplexml simplexml@noreply.github.com 
 Sent: Sunday, 28 August 2016, 15:16
 Subject: [ngallagher/simplexml] Help with resolving anonymous namespaces? (#14)

I have an xml like this<root>
  <item>
    media:thumbnailthumbnail_url/media:thumbnail
  </item>
</root>
I can't seem to find a way how to parse such xml correctly.
Now I'm using such class:@Root(name = "item")
public class ArticleSummary {

```
@Element
@Namespace(prefix = "media")
private String thumbnail;
```

}
But I'm keep getting XmlPullParserException: undefined prefix: media error.What should I do differently?—

**Comment by mjurkus** [comment]
I tried different combinations. But I can't get it working. 
I understand that exception is from XML parser, but why doesn't it get namespace definitions?

**Comment by ngallagher** [comment]
You cannot parse invalid xml you need to declare the namespace
import junit.framework.TestCase;
import org.simpleframework.xml.Element;import org.simpleframework.xml.Namespace;import org.simpleframework.xml.Root;import org.simpleframework.xml.core.Persister;
public class NamespaceTest extends TestCase{      private static final String SOURCE =   "<root xmlns:media='blah'>"+   "  <item>"+   "    media:thumbnailthumbnail_url/media:thumbnail"+   "  </item>"+   "</root>";          @Root(name = "item")   public static class ArticleSummary {
       @Element       @Namespace(prefix="media", reference="blah")        private String thumbnail;   }        @Root   public static class Article{      @Element      private ArticleSummary item;   }      public void testXml() throws Exception {      Persister persister = new Persister();      Article article = persister.read(Article.class, SOURCE);      System.err.println(article.item.thumbnail);   }
}

```
  From: Niall Gallagher <gallagher_niall@yahoo.com>
```

 To: ngallagher/simplexml reply@reply.github.com; ngallagher/simplexml simplexml@noreply.github.com 
 Sent: Sunday, 28 August 2016, 15:41
 Subject: Re: [ngallagher/simplexml] Help with resolving anonymous namespaces? (#14)

You need to define the namespace, @Namespace(prefix="x", reference="http://mynamespace"), fyi this exception is thrown from the XML parser not Simple XML.

```
  From: Martynas Jurkus <notifications@github.com>
```

 To: ngallagher/simplexml simplexml@noreply.github.com 
 Sent: Sunday, 28 August 2016, 15:16
 Subject: [ngallagher/simplexml] Help with resolving anonymous namespaces? (#14)

I have an xml like this<root>
  <item>
    media:thumbnailthumbnail_url/media:thumbnail
  </item>
</root>
I can't seem to find a way how to parse such xml correctly.
Now I'm using such class:@Root(name = "item")
public class ArticleSummary {

```
@Element
@Namespace(prefix = "media")
private String thumbnail;
```

}
But I'm keep getting XmlPullParserException: undefined prefix: media error.What should I do differently?—

**Comment by mjurkus** [comment]
So if XML is not valid there is no way around that?

**Comment by Kisty** [comment]
Doesn't look like there is. 

The only solution that you could try is to manipulate the XML manually after downloading the XML but _before_ parsing it. This way, you don't have to change the server.

You could for instance search for "media" and put a valid namespace at the root so it looks something like:

```
<root media:xmlns="http://example.com/media">
  <item>
    <media:thumbnail>thumbnail_url</media:thumbnail>
  </item>
</root>
```

Failing that, you could remove the media namespace altogether which would be easier.

```
<root>
  <item>
    <thumbnail>thumbnail_url</thumbnail>
  </item>
</root>
```

**Comment by mjurkus** [comment]
Thank you for suggestion.
