### ISSUE TITLE
org.simpleframework.xml.convert.RegistryStrategyTest consistently fails on java8

### ISSUE THREAD

**Issue by Boskovits** [ngallagher/simplexml#33]
Testsuite: org.simpleframework.xml.convert.RegistryStrategyTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.165 sec
------------- Standard Output ---------------
<a:petShop xmlns:a="http://domain/a">
   <b:pets xmlns:b="http://domain/b">
      <pet class="org.simpleframework.xml.convert.ExampleConverters$Cat">
         <name>Kitty</name>
         <age>2</age>
      </pet>
      <pet class="org.simpleframework.xml.convert.ExampleConverters$Dog" name="Lassie" age="10"/>
   </b:pets>
</a:petShop>------------- ---------------- ---------------

Testcase: testConverter took 0.159 sec
	FAILED
Document does not match expression '/petShop/pets/pet[1]' with attribute name='Lassie' for <a:petShop xmlns:a="http://domain/a">
   <b:pets xmlns:b="http://domain/b">
      <pet class="org.simpleframework.xml.convert.ExampleConverters$Cat">
         <name>Kitty</name>
         <age>2</age>
      </pet>
      <pet class="org.simpleframework.xml.convert.ExampleConverters$Dog" name="Lassie" age="10"/>
   </b:pets>
</a:petShop>
junit.framework.AssertionFailedError: Document does not match expression '/petShop/pets/pet[1]' with attribute name='Lassie' for <a:petShop xmlns:a="http://domain/a">
   <b:pets xmlns:b="http://domain/b">
      <pet class="org.simpleframework.xml.convert.ExampleConverters$Cat">
         <name>Kitty</name>
         <age>2</age>
      </pet>
      <pet class="org.simpleframework.xml.convert.ExampleConverters$Dog" name="Lassie" age="10"/>
   </b:pets>
</a:petShop>
	at org.simpleframework.xml.ValidationTestCase.assertMatch(ValidationTestCase.java:179)
	at org.simpleframework.xml.ValidationTestCase.assertElementHasAttribute(ValidationTestCase.java:146)
	at org.simpleframework.xml.convert.RegistryStrategyTest.testConverter(RegistryStrategyTest.java:69)

**Comment by Boskovits** [comment]
Sorry, I had some formatting issue with my previous comment, I will attach te report instead.
[TEST-org.simpleframework.xml.convert.RegistryStrategyTest.txt](https://github.com/ngallagher/simplexml/files/1780388/TEST-org.simpleframework.xml.convert.RegistryStrategyTest.txt)

**Comment by Boskovits** [comment]
#15 Fixes this

**Comment by ngallagher** [comment]
This works now
