### ISSUE TITLE
Android Storage Access Framework support

### ISSUE THREAD

**Issue by bruenor41** [ngallagher/simplexml#38]
Hi, I use this amazing library several years on android. But google announced changes in android q and next android versions about writing to storage.

https://www.androidcentral.com/what-scoped-storage-android-q
https://developer.android.com/training/data-storage/files/external-scoped

Would be possible add support for writing files with SAF? I have experiences with this framework I can help.

https://commonsware.com/blog/2019/06/05/storage-access-framework-counterpoints.html

**Comment by Kisty** [comment]
I would argue this goes beyond the scope of the library. SimpleXML is a
pure java library not linked with Android so can be used in Java apps as
well as Android. If I remember correctly, you can give SimpleXML an
input/output stream (I've forgot which one). You have to do the storage
access framework work. It's not too hard once you know what you're doing.

What problem are you trying to solve?

**Comment by bruenor41** [comment]
Aah, correct, how could I miss method with stream parameter, that's correct solution. I write xml files to internal storage outside private folder with File class parameter, now I must fix it due SAF complication on android 10+. Many thanks :)

**Comment by Kisty** [comment]
You're welcome! Feel free to to close the issue
